---
title: "scType"
subtitle: "Cell type Annotation"
author: "Sung Rye Park"
date: "`r format(Sys.Date())`"
output: 
  html_document:
    code_folding: none
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, warning=FALSE, message=FALSE, results = "markup")
options(warn = F)

library(ggplot2)
library(ggrepel)
library(dplyr)
library(Seurat)
library(scCustomize)
library(SingleCellExperiment)
library(SeuratWrappers)
```

```{r, echo=FALSE}
dir <- "~/Desktop/Uconn/ASPM_Mouse/"
obj.srt = readRDS(paste0(dir,"rds/WT_umi5000_mito5.obj_singlet.rds"))
```

<hr>

Packages 

* scType

## scType {.tabset}

### Processing 
```{r}
library(HGNChelper)
library(openxlsx)

source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"); source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")

gs_list <- gene_sets_prepare("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_short.xlsx", "Brain") # e.g. Immune system, Liver, Pancreas, Kidney, Eye, Brain

```

```{r}
cluster_resolution = "RNA_snn_res.0.4"
# extract scaled scRNA-seq matrix
seurat_package_v5 <- isFALSE('counts' %in% names(attributes(obj.srt[["RNA"]])));
scRNAseqData_scaled <- if (seurat_package_v5) as.matrix(obj.srt[["RNA"]]$scale.data) else as.matrix(obj.srt[["RNA"]]@scale.data)

# run ScType
es.max <- sctype_score(scRNAseqData = scRNAseqData_scaled, 
                       scaled = TRUE, 
                       gs = gs_list$gs_positive, 
                       gs2 = gs_list$gs_negative)

cL_results <- do.call("rbind", lapply(unique(obj.srt@meta.data[, cluster_resolution]), function(cl) {
  cl_cells <- rownames(obj.srt@meta.data[obj.srt@meta.data[, cluster_resolution] == cl, ])
  
  # Maximum scores of each clusters
  es.max.cl <- sort(rowSums(es.max[, cl_cells]), decreasing = TRUE)
  
  # data frame
  df <- data.frame(
    cluster = cl,
    type = names(es.max.cl),
    scores = es.max.cl,
    ncells = sum(obj.srt@meta.data[, cluster_resolution] == cl)
  )
  
  # top 10
  return(head(df, 10))
}))

# cL_results %>% saveRDS(paste0(dir, "rds/cL_results.rds"))
sctype_scores <- cL_results %>% group_by(cluster) %>% top_n(n = 5, wt = scores) 
sctype_scores <- sctype_scores %>% filter(scores> 0)
```


### scType Score {.tabset}

#### Table 
```{r}
sctype_scores$cluster = paste0("cluster ", sctype_scores$cluster)
sctype_scores %>% DT::datatable(extensions = "Buttons",
                              filter = 'bottom',
                              width = "800px",
                options = list(autoWidth = TRUE, 
                               fixedHeader = TRUE,
                               dom="Bfrtip", buttons=c("csv","excel")))
```

#### Score plot 

```{r, fig.width=12, fig.height=6}
df = sctype_scores
df$cluster = factor(df$cluster, levels = c(paste0("cluster ", 0:17)))
df %>% ggplot(aes(cluster, scores, fill=type)) + 
  geom_col(position = "dodge2", color="grey7", linewidth =0.1) +
  theme_bw() +
  RotatedAxis()
```

#### Score plot2  
```{r, fig.width=12, fig.height=12}
df = sctype_scores
df$cluster = factor(df$cluster, levels = c(paste0("cluster ", 0:17)))
df %>% ggplot(aes(cluster, scores, fill=type)) + 
  geom_col(position = "dodge2", color="grey7", linewidth =0.1) +
  theme_bw() +
  facet_wrap(.~type, ncol = 3) +
  RotatedAxis()
```

#### Vlnplot 
```{r, fig.width=8, fig.height=12}
es.max.t = t(es.max)
es.max.t = es.max.t[colnames(obj.srt),] %>% as.data.frame()

obj.srt = AddMetaData(object = obj.srt, metadata = es.max.t)
VlnPlot(obj.srt, group.by = "RNA_snn_res.0.4",
        features = c("Cholinergic neurons",
                     "Dopaminergic neurons",
                     "Endothelial cells",
                     "GABAergic neurons",
                     "Glutamatergic neurons",
                     "Immature neurons",
                     "Mature neurons",
                     "Microglial cells",
                     "Myelinating Schwann cells",
                     "Neural Progenitor cells",
                     "Oligodendrocyte precursor cells",
                     "Oligodendrocytes",
                     "Radial glial cells",
                     "Schwann precursor cells",
                     "Serotonergic neurons"), 
        stack = T, flip = T, sort = T) +NoLegend()
```

### Scoring correlation {.tabset}

#### Processing
```{r}
es.max.t = t(es.max)
es.max.t = es.max.t[colnames(obj.srt),] %>% as.data.frame()
# obj.srt = AddMetaData(object = obj.srt, metadata = es.max.t)
```

```{r}
input.mtx= es.max.t
test.cor <- WGCNA::cor(input.mtx, use = 'pairwise.complete.obs')
#test.cor <- WGCNA::cor(input.mtx %>% t(), use = 'pairwise.complete.obs')

my.colors <- c(colorRampPalette(colors = c("navy","white"))(15), 
               colorRampPalette(colors = c("white","red"))(30))
# test.cor %>% pheatmap::pheatmap(color = my.colors)
```

#### Correlation Heatmap
```{r, fig.width=8.5, fig.height=8}
p =test.cor %>% pheatmap::pheatmap(color = my.colors)
```

#### Correlation table
```{r}
test.cor[p$tree_row$order,p$tree_col$order] %>% 
  DT::datatable(extensions = "Buttons",
                              filter = 'bottom',
                              width = "800px",
                options = list(autoWidth = TRUE, 
                               fixedHeader = TRUE,
                               pageLength= 22,
                               scrollX=T,
                               dom="Bfrtip", buttons=c("csv","excel")))
```


```{r, eval=FALSE, echo=FALSE}
df = obj.srt@meta.data
df %>% ggplot(aes(singleR_label, `Neural stem cells`)) + geom_col() +RotatedAxis()
df %>% ggplot(aes(singleR_label, `Radial glial cells`)) + geom_col() +RotatedAxis()

```


<br>
<hr>
<br>
```{r}
sessionInfo()
```


