---
title: "Apartment Search in AA"
author: "Sung Rye Park"
date: "`r format(Sys.Date())`"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, eval =T, fig.align = "left", 
                      message=F, warning=F,
                      results = "markup",
                      error = TRUE,
                      highlight = TRUE,
                      prompt = FALSE,
                      tidy = FALSE)
```

## Apartment


### The Pines of Cloverlane  

* 4907 Cloverlane St, Ypsilanti, MI 48197
* [application link](https://thepinesofcloverlane.securecafe.com/onlineleasing/the-pines-of-cloverlane-apartments/guestlogin.aspx?PropLeadSource_455324=portal&RCStandardCampaignId_455324=455839&_yTrackUser=Mjk4NDYxMjE0OSMxNDc0MDAwMDEx-%252fmRXgLi2KsE%253d&_yTrackVisit=NDk2MDAxODA4OSMxMTc4MDcyNzY3-AYVnHSExSEE%253d&_yTrackReqDT=19211220241608)
* 7348879015

<!-- * Reviews are pretty bad since 2022.  -->

<hr><br><br><br>


### Ann Arbor Woods

* 2167 Medford Rd, Ann Arbor, MI 48104 
* (734) 821-2662
* (833) 482-6902
* [Apartment.com link](https://www.apartments.com/ann-arbor-woods-ann-arbor-mi/qswnlmz/)
* [link](https://www.annarborwoodsapartments.com/)
* Administrative Fee $150 Application Fee $75
* Cat One Time Fee $300 Monthly Pet Rent $30
* Utility not included
* One unit available at apartment.com 
  * 02-40 (2B/1BR), $1,438, 800 sqft
  * availibility Oct. 22


<br><br>

### ~~Pine Valley Apartments~~

* 1521 Pine Valley Blvd, Ann Arbor, MI 48104
* On Packard St
* [link](https://www.apartments.com/pine-valley-apartments-ann-arbor-mi/63d3fsr/#reviewsSection)
* $1,300 - $2,100 
* 2 Bedroom $1,500 - $1,530
* Application Fee $60
* Reservation fee $250 
* Maybe I take 1B or 2B
* 734.971.5210
* info@pinevalleyapartments.com




### ~~Spruce Knob~~

* 2960 Birch Hollow Dr, Ann Arbor, MI 48108
* McKinley Properties
* 844-621-3396
* $1429~1629 for 2B
* $1329 for 1B one available ~~09-06-2024~~
* Left the message via webpage on 24.08.11 
* No availability on Oct 24.08.14
* [homepage](https://www.mckinley.com/apartments/michigan/ann-arbor/spruce-knob/contact/)


### Evergreen Apartment 

* The windows are positioned high (I don't like this)
* Near Kroger/Aldi
* 3089 Woodland Hills Dr, Ann Arbor, MI 48108
* McKinley Properties
* 866-696-5505
* Left the message via webpage on 24.08.11 
* [homepage](https://www.mckinley.com/apartments/michigan/ann-arbor/evergreen/contact/)


### Ridgewood Apartment 

* [homepage](https://peak-management.com/ridgewood/)
* (734) 971-0635
* Near Aldi
* 4141 Green Meadows Boulevard, Ypsilanti, MI 48197
* $1,429 - $1,574
* Administative Fee $150, Applicatioin $50
* [Apartment.com](https://www.apartments.com/ridgewood-apartments-ypsilanti-mi/pdf09jt/)





### The Ivanhoe Apartments

* 1529-1537 Pine Valley Blvd, Ann Arbor, MI 48104 (next to Pine Valley Apartment)
* On Packard St
* (844) 572-0518 Homepage
* (734) 390-4150
* Application Fee $50
* [link](https://www.apartments.com/the-ivanhoe-apartments-ann-arbor-mi/t2dmrl9/)
* Pet $350 one time, $30 monthly


### Meadows

* 1606-1890 Meadow Woods Blvd, Ypsilanti, MI 48197
* (734) 887-1650






### Hamptons of Cloverlane Apartments

* 3103 Homestead Commons Dr, Ann Arbor, MI 48108 (very close to King George Blvd)
* Not sure 
* [Apartment.com link](https://www.apartments.com/hamptons-of-cloverlane-apartments-ypsilanti-mi/rtgqc22/#reviewsSection)
* Application fees  <br>
  Administrative Fee
  $150<br>
  Application Fee
  $85<br>
  Monthly Pet Rent $30 <br>
  One Time Fee $325 <br>

