---
title: "Work Tracking (BCH)"
subtitle: "Sung Rye Park"
author: ""
date: "`r format(Sys.Date())`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<hr>

### BCH 

ch261670<br>

* [The Hub](http://web2.tch.harvard.edu/index.html)
* [HR (from Hub)](http://web2.tch.harvard.edu/hr/)
* [kronos (UKG) home](http://web2.tch.harvard.edu/kronos/index.html)
  * [UKG](https://childrensharvard-sso.prd.mykronos.com/wfd/home) Time Reporting
* [peoplesoft : employee-self-service](http://web2.tch.harvard.edu/PeopleSoftERP/mainpageS2740P11.html)
  * benefit enrollment by Sep 12th <br><br>
* [IT help desk](http://web2.tch.harvard.edu/ehelp/) 
  * email help.desk@childrens.harvard.edu
  * email hrhub@childrens.harvard.edu 
  * call 617-355-7780 <br><br>
* [chbwiki](https://chbwiki.tch.harvard.edu/) : Information Technology Wiki at Boston Children's Hospital!

<hr>

### TEAM work repository

* [Google workspace](http://drive.bchresearch.org/)
  * sung-rye.park@enders.tch.harvard.edu 
  * (note: different name from bch email)<br><br>
* [Google drive](https://drive.google.com/drive/folders/0AHMB3WsvXf9LUk9PVA) Request needed.<br><br>
* [dst-bioinfo: gitlab](https://tier1git.aws.chboston.org/dst-bioinfo)
  * You have been granted access to the DST-Bioinfo group with the following role: 
  * Maintainer. This is a default role. 
  * 240813 (GitLab <gitlab@tier1git.aws.chboston.org>)<br>
* [rc-dst: gitlab](https://rc-gitlab.chboston.org/rc-dst)

* [Smartsheet Portal](https://rc-intweb1.chboston.org/Scholar/smartsheet.php)
  * Smartsheet Enrollment Form
  * [Smartsheet: BCH RC ALL](https://app.smartsheet.com/workspaces/QqH4VCGh6VwH24V5qpvg3JP3Xx7Xv4fR2qH4xhp1)
<br><br>

<hr>

### Training 

* [Net Learning](https://lms.healthcaresource.com/MyNetLearning/Activities)<br>
  Two HIPAA training first for HPC access request (completed)
* [CITI Training](https://www.citiprogram.org/)
  * Sung Rye Park (ID 13532931) (completed)
  * [pdf] BCH/onboarding/training/citiCompletionCertificate_13532931_64356974.pdf


<hr>

### HPC access 

* [In process] 24.08.13

<br><br><br><br>
