---
title: "FOG in Boston 2024"
subtitle: "Personl Note"
author: "Sung"
output: 
  html_document:
    theme: cosmo
    highlight: monochrome
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
```

<br><br>

### THE FESTIVAL OF GENOMICS & BIODATA    

[Event Main Page Link](https://festivalofgenomics.com/boston/en/page/boston-home)
<br><br><br>


### **Notes** 


#### **Giotto**

* [Giotto tutorial](https://giottosuite.readthedocs.io/en/latest/)
* An open-source and technology-agnostic spatial multi-omics analysis platform
* [Seq-scope Tutorial using Giotto](https://giottosuite.readthedocs.io/en/latest/subsections/datasets/seqscope_mouse_liver_221115.html)
  * Seq-scope : now the resolution of this technique is 0.5um. 
  * [pub](https://lee.lab.medicine.umich.edu/seq-scope)
  * [Spatial Transcriptomic Tools (STtools)](https://github.com/jyxi7676/STtools)

<br><br>

#### **Monkeybread by Ming Tang**

* [Monkeybread Tutorial](https://monkeybread.readthedocs.io/en/v0.6.0/notebooks/tutorial.html#) 
  * python
  * Tool for analyzing **cell closeness in spatial transcriptomic data**. Developed at Immunitas Therapeutics.
<br><br>

#### Nanovials 

* [Partillion Bioscience](https://www.partillion.com/technology)
* Nanovials are nanoliter-sized particles that act as millions of suspendable wells for individual cells. 
* For secretome

<br><br>

#### **Sanofi Presentation**

[Spatial Transcriptomics Application](FB24/FestivalBoston24_Sanofi.html)

* Understanding Tumor Microenvironment in ER+ Breast Cancer using 10x Genomics (Xenium in situ)
* Spatial Neighborhood analysis

<hr>

#### **Astrazeneca Presentation**

[Osimertinib and Drug Tolerant Persister (DTP) Cellls](FB24/FestivalBoston24_AZ.html)<br>
<hr>

#### **Takeda Presentation**

[Single Cell Data Analysis (Bioinformatics Landscape)](FB24/FestivalBoston24_Takeda.html)

* Batch Correction
* Data Integration
* Cell Identities

<hr>

#### **Moderna Presentation**

[mRNA vaccine]()
<hr>
**Single Cell Worksop**

[link]()
<hr>
<br><br><br><br>

<!-- <br> Update: "`r format(Sys.Date())`" -->