---
title: "scRNA-seq workflow"
subtitle: " "
#date: "`r format(Sys.Date())`"
output:
  html_document:
    toc: true
    toc_depth: 6
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = F)
```

[Link to the version1](https://sung2021.github.io/samplePages/scRNAseq.html)  <br>
<hr>

### Initial Processing  

* [**QC processing and initial filitering**](scRNA_preprocessing.html)
  * UMI cutoff
  * mitochondrial DNA cutoff
  * Doublet Removal (scrublet)
  * Filtered sample plots
  * Subset samples

### Integration

  * [**Harmony**](scRNA_integration_harmony.html)
    * Preprocessing before integration
    * Harmony integration
  
### Clustering Ananlysis 

  * [**UMAP/Clustering/Marker Genes**](scRNA/scRNA_UMAP.html)
    * UMAP colored by conditions
    * Number of cells by cluster
    * Sankey plot of 2+ resolutions 
    * Marker genes by clusters
  * [**GSEA**](scRNA/scRNA_GSEA.html)
    * GSEA by cluster marker genes
      * BP
      * MF
      * CC
    * GSEA info table

### Cell type annotation  

<!-- &nbsp;&nbsp;&nbsp;&nbsp;Immune cell type -->
 
  
  * [**Annotation by scType**](scRNA/scRNA_scType.html)
  * [**Annotation by singleR**](scRNA/scRNA_singleR.html)
  * [Reference geneset](scRNA/annotation_reference.html)
  <!-- * [**Manual Annotation**](scRNA/Daiichi2024_30342.24.05.12.suggestedAnnotation.html)    -->

### Trajectory by monocle3
  * Trajectory graph

<hr>

### Further Analysis  

  * [**Population changes**](scRNA/Daiichi2024_30342.24.05.12.analysis_population.html)
  
<br><br><br><br><br>